name: Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js (if needed, e.g., for build tools)
      uses: actions/setup-node@v2
      with:
        node-version: '14' # specify your node version

    - name: Install dependencies
      run: npm install
      # or skip if no dependencies

    - name: Build the website
      run: npm run build
      # adjust according to your build command

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        # replace ./build with your build output directory
